[package]
name = "marlin"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow            = "1.0"
clap              = { version = "4.5.2", features = ["derive"] }
directories       = "5.0"
glob              = "0.3"
rusqlite          = { version = "0.31.0", features = ["bundled"] }
tracing           = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
walkdir           = "2.5"
